#H2 Database
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
spring.jpa.generate-ddl=true
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/jobapp
spring.datasource.username=deven065
spring.datasource.password=@Krishna2000
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

spring.application.name=job-application

#Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.info.env.enabled=true
info.app.name=JobApplication
info.app.description=Job app built be Deven
info.app.version=1.0.0

management.endpoint.shutdown.enabled=true
server.shutdown=graceful